apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: func-app-secret
          # env:
          #   # This is not required when using triggerauthentication object
          #   - name: keda-secret
          #     valueFrom:
          #       secretKeyRef:
          #         name: queue-policy-secret
          #         key: connection-string
